from qgrtsys.if_host.python import *

if_quingo = If_Quingo()

def gen_ran_num(nr_rep):
    if_quingo.call_quingo("kernel.qu", 'gen_ran_seq', nr_rep)
    res = if_quingo.read_result()
    print(res)

gen_ran_num(10)

# for nr_rep in range(10, 22):
#     gen_ran_num(nr_rep)

# res_array = []
# for i in range(1, 16, 3):
#     if if_quingo.call_quingo("kernel.qu", 'gen_ran_seq', i) is True:
#         res = if_quingo.read_result()
#         res_array.append(res)

#     else:
#         print("Fail to call the kernel.")

# print("The random number sequences generated by Quingo are:")
# for i in range(len(res_array)):
#     for ele in res_array[i]:
#         print("{:5}, ".format(ele), end='')
#     print("")
